-- SOCIAL outbox: durable correlation + reconciliation of asynchronous (Buffer) publishes.
-- Idempotent; additive only. We do NOT edit 20260831000000/20260831010000 — both are already
-- applied in prod and rewriting an applied migration causes file-vs-prod drift.

-- (1) Guarded uniqueness on (brand_id, dedup_key).
--     20260831010000 creates this index unguarded, which fails on any database that already
--     accumulated duplicate keys under the earlier NON-unique index from 20260831000000. Do the
--     deterministic cleanup here so a environment that has not yet converged still can:
--     keep the OLDEST campaign per (brand_id, dedup_key) — it owns any social_post rows and the
--     spend already attributed to it — and drop the later duplicates.
delete from social_campaign c
using social_campaign keep
where c.brand_id = keep.brand_id
  and c.dedup_key = keep.dedup_key
  and (keep.created_at, keep.id) < (c.created_at, c.id);

create unique index if not exists social_campaign_brand_dedup_uk
  on social_campaign (brand_id, dedup_key);

-- (2) Correlation key, generated by US before the external publish and persisted with the
--     'pending' outbox row. It is sent to the provider in the post `source` field, so a submission
--     whose response we lost can still be tied back to the row that reserved it.
alter table social_post add column if not exists idem_key text;

-- (3) Reconciler support: `submitted_at` records when the provider actually accepted the post, so
--     the sweep only polls submissions old enough to have settled, and `attempts` bounds retries.
alter table social_post add column if not exists submitted_at timestamptz;
alter table social_post add column if not exists reconcile_attempts int not null default 0;

-- (4) The reconciler's working set: pending rows, oldest first. Partial index — 'pending' is a
--     small, transient slice of the table, so this stays tiny no matter how much history accrues.
create index if not exists social_post_pending_reconcile
  on social_post (created_at) where status = 'pending';
